### ISSUE TITLE
S3 could not be resolved (110: Operation timed out)

### ISSUE THREAD

**Issue by rcdelacruz** [jamescmartinez/nginx-s3-upload#1]
I got the ff issues, can you help find what is wrong pls? :)
 
gsvs3pd01.s3.amazonaws.com could not be resolved (110: Operation timed out), client: 120.28.112.39, server: _, request: "PUT /uploads/entity/property/09176214691 HTTP/1.1", host: "52.76.22.22"

**Comment by jamescmartinez** [comment]
Hi @rcdelacruz -- I think your best bet would be to ask on StackOverflow since this is not necessarily specific to this project. Good luck!
